# Перенаправление HTTP на HTTPS
server {
    listen 80;
    server_name drugizpriyuta.ru www.drugizpriyuta.ru;

    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}

# Основной HTTPS сервер
server {
    listen 443 ssl;
    server_name drugizpriyuta.ru www.drugizpriyuta.ru;

    ssl_certificate /etc/letsencrypt/live/drugizpriyuta.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/drugizpriyuta.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://site:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /app/media/;
    }
}