server {
    listen 80;
    server_name drugizpriyuta.ru www.drugizpriyuta.ru;

    location / {
        proxy_pass http://site:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/;
    }
}