# Generated by Django 5.2.4 on 2026-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Месяц и год отчета', verbose_name='Месяц отчета')),
                ('income', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Приход')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Расход')),
                ('expense_details', models.TextField(verbose_name='Подробный расход')),
                ('donors', models.TextField(verbose_name='Список жертвователей')),
            ],
        ),
    ]
