# Generated by Django 5.2.4 on 2026-03-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
