# Generated by Django 5.2.4 on 2026-03-20 12:25

import django.db.models.deletion
import dogs.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '__first__'),
        # ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя животного', max_length=64, verbose_name='Имя')),
                ('color', models.CharField(help_text='Окрас животного', max_length=128, verbose_name='Окрас')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], default='M', help_text='Пол животного', max_length=1, verbose_name='Пол')),
                ('is_neutered', models.BooleanField(default=False, help_text='Кастрировано? Да/Нет(по умолчанию)', verbose_name='Кастрация')),
                ('birth_date', models.DateField(help_text='Ориентировочная дата рождения (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата рождения')),
                ('intake_date', models.DateField(help_text='Ориентировочная дата заселения в приют (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата заселения в приют')),
                ('is_at_shelter', models.BooleanField(default=True, help_text='Находится в приюте? Да(по умолчанию)/Нет', verbose_name='Находится в приюте')),
                ('outtake_date', models.DateField(blank=True, help_text='Дата убытия из приюта', null=True, verbose_name='Дата убытия из приюта')),
                ('outtake_reasons', models.TextField(blank=True, help_text='Причина убытия', null=True, verbose_name='Причина убытия')),
                ('intake_place', models.TextField(blank=True, help_text='Откуда животное попало в приют?', null=True, verbose_name='Место изъятия')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('kennel', models.CharField(blank=True, choices=[('P1', 'П1'), ('P2', 'П2'), ('P3', 'П3'), ('P4', 'П4'), ('P5', 'П5'), ('P6', 'П6'), ('P7', 'П7'), ('P8', 'П8'), ('P9', 'П9'), ('P10', 'П10'), ('P11', 'П11'), ('P12', 'П12'), ('P13', 'П13'), ('P14', 'П14'), ('P15', 'П15'), ('P16', 'П16'), ('P17', 'П17'), ('P18', 'П18'), ('P19', 'П19'), ('P20', 'П20'), ('G1', 'Г1'), ('G2', 'Г2'), ('G3', 'Г3'), ('G4', 'Г4'), ('G5', 'Г5'), ('G6', 'Г6'), ('G7', 'Г7'), ('G8', 'Г8'), ('G9', 'Г9'), ('G10', 'Г10'), ('G11', 'Г11'), ('G12', 'Г12'), ('G13', 'Г13'), ('G14', 'Г14'), ('G15', 'Г15'), ('G16', 'Г16'), ('G17', 'Г17'), ('KSH1', 'КШ1'), ('KSH2', 'КШ2'), ('KSH3', 'КШ3'), ('KSH4', 'КШ4'), ('KSH5', 'КШ5'), ('KSH6', 'КШ6'), ('KSH7', 'КШ7'), ('KSH8', 'КШ8'), ('KSH9', 'КШ9'), ('GUARD', 'Охрана'), ('Mira', 'Мира'), ('FOSTER', 'Передержка')], default=None, help_text='Вольер', max_length=64, null=True, verbose_name='Вольер')),
                ('height', models.CharField(choices=[('Low', 'ниже колена'), ('Mid', 'по колено'), ('High', 'выше колена')], default='Mid', max_length=4, verbose_name='Рост собаки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='database.owner', verbose_name='Владелец')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.CreateModel(
            name='DogHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Хронические заболевания (необязательный пункт)', null=True, verbose_name='Хронические заболевания')),
                ('treatment', models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле), дописываем, не удаляя старое: даты, лекарство, дозировка,будет своеобразный архив', null=True, verbose_name='Назначенное лечение')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog_health', to='dogs.doginfo')),
            ],
            options={
                'verbose_name': 'Здоровье собаки',
                'verbose_name_plural': 'Здоровье собак',
            },
        ),
        migrations.CreateModel(
            name='DogDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='История появления животного в приюте', verbose_name='Биография')),
                ('character', models.TextField(help_text='Характер животного', verbose_name='Характер')),
                ('best_owner', models.TextField(blank=True, help_text='Кому подойдет (необязательное поле)', null=True, verbose_name='Лучшие владельцы для животного')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog_description', to='dogs.doginfo')),
            ],
            options={
                'verbose_name': 'Описание собаки',
                'verbose_name_plural': 'Описания собак',
            },
        ),
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=dogs.models.dog_image_upload_to, verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dogs.doginfo', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фотография собаки',
                'verbose_name_plural': 'Фотографии собак',
            },
        ),
    ]
