# Generated by Django 5.2.4 on 2026-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='full_url',
            field=models.CharField(default='/media/blog_images/изображение_2026-03-20_221328730.png', help_text='Ссылка для копирования в блог', max_length=128, verbose_name='Полный URL'),
            preserve_default=False,
        ),
    ]
