# Generated by Django 5.2.4 on 2026-03-21 09:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogimage_full_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='full_url',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.blog_image_upload_path, verbose_name='Изображение'),
        ),
    ]
