# Generated by Django 5.2.4 on 2026-03-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Описание тега', null=True, verbose_name='Теги')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Месяц и год отчета', verbose_name='Месяц отчета')),
                ('income', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Приход')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Расход')),
                ('expense_details', models.TextField(verbose_name='Подробный расход')),
                ('donors', models.TextField(verbose_name='Список жертвователей')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя', max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия', max_length=64, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, help_text='Отчество', max_length=128, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона', max_length=64, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, help_text='Адрес владельца', max_length=128, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='TaggedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='database.animaltag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
