# Generated by Django 5.2.4 on 2026-03-24 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0002_auto_20260325_0403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.AlterModelOptions(
            name='animaltag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='taggedanimal',
            options={'verbose_name': 'Животное с тегом', 'verbose_name_plural': 'Животные с тегами'},
        ),
        migrations.AlterField(
            model_name='animaltag',
            name='description',
            field=models.TextField(blank=True, help_text='Описание тега', null=True, verbose_name='Описание тега'),
        ),
        migrations.AlterField(
            model_name='animaltag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animaltag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='animaltag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggedanimal',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedanimal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggedanimal',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='taggedanimal',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='database.animaltag', verbose_name='Тег'),
        ),
    ]
