# Generated by Django 3.2.3 on 2025-03-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20250322_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathealth',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathealth', to='database.catinfo'),
        ),
        migrations.AlterField(
            model_name='catinfo',
            name='description',
            field=models.TextField(blank=True, help_text='Описание животного', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doghealth',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dohhealth', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='description',
            field=models.TextField(blank=True, help_text='Описание животного', null=True, verbose_name='Описание'),
        ),
    ]
