# Generated by Django 5.2.4 on 2025-11-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20250323_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathealth',
            name='treatment',
            field=models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле), дописываем, не удаляя старое: даты, лекарство, дозировка,будет своеобразный архив', null=True, verbose_name='Назначенное лечение'),
        ),
        migrations.AlterField(
            model_name='doghealth',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doghealth', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='doghealth',
            name='treatment',
            field=models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле), дописываем, не удаляя старое: даты, лекарство, дозировка,будет своеобразный архив', null=True, verbose_name='Назначенное лечение'),
        ),
        migrations.CreateModel(
            name='DogDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='История появления животного в приюте', verbose_name='Биография')),
                ('character', models.TextField(help_text='Характер животного', verbose_name='Характер')),
                ('best_owner', models.TextField(blank=True, help_text='Кому подойдет (необязательное поле)', null=True, verbose_name='Лучшие владельцы для животного')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogdescription', to='database.doginfo')),
            ],
            options={
                'verbose_name': 'Описание собаки',
                'verbose_name_plural': 'Описания собак',
            },
        ),
    ]
