# Generated by Django 5.2.4 on 2025-11-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_cathealth_treatment_alter_doghealth_dog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfo',
            name='height',
            field=models.CharField(choices=[('Low', 'Ниже колена'), ('Mid', 'По колено'), ('High', 'Выше колена')], default='Mid', max_length=4, verbose_name='Рост собаки'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='height',
            field=models.CharField(choices=[('Low', 'Ниже колена'), ('Mid', 'По колено'), ('High', 'Выше колена')], default='Mid', max_length=4, verbose_name='Рост собаки'),
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_photos/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='database.doginfo')),
            ],
            options={
                'verbose_name': 'Фотография собаки',
                'verbose_name_plural': 'Фотографии собак',
            },
        ),
    ]
