# Generated by Django 5.2.4 on 2025-11-07 08:42

import database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_catinfo_height_doginfo_height_animalphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='catinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='doginfo',
            name='description',
        ),
        migrations.AlterField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='database.doginfo', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='animalphoto',
            name='image',
            field=models.ImageField(upload_to=database.models.dog_image_upload_to, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='dogdescription',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_description', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='doghealth',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_health', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='height',
            field=models.CharField(choices=[('Low', 'ниже колена'), ('Mid', 'по колено'), ('High', 'выше колена')], default='Mid', max_length=4, verbose_name='Рост собаки'),
        ),
    ]
