# Generated by Django 5.2.4 on 2025-11-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_rename_animalphoto_dogphoto_catdescription_catphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catdescription',
            old_name='dog',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='cathealth',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_health', to='database.catinfo'),
        ),
    ]
