# Generated by Django 5.2.4 on 2025-11-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_dog_catdescription_cat_alter_cathealth_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathealth',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_health', to='database.catinfo'),
        ),
    ]
