# Generated by Django 5.2.4 on 2025-11-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_cathealth_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catdescription',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_description', to='database.catinfo'),
        ),
        migrations.AlterField(
            model_name='dogdescription',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog_description', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='doghealth',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog_health', to='database.doginfo'),
        ),
    ]
