# Generated by Django 3.2.3 on 2025-03-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Хронические заболевания (необязательный пункт)', null=True, verbose_name='Хронические заболевания')),
                ('treatment', models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле)', null=True, verbose_name='Назначенное лечение')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('felv_status', models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Лейкоз у кисы: да(по умолчанию)/нет', max_length=1, verbose_name='Вирус лейкоза кошек')),
                ('fiv_status', models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Иммунодефицит у кисы: да(по умолчанию)/нет', max_length=1, verbose_name='Иммунодефицит')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cathealth', to='database.catinfo')),
            ],
            options={
                'verbose_name': 'Здоровье кошки',
                'verbose_name_plural': 'Здоровье кошек',
            },
        ),
        migrations.CreateModel(
            name='DogHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Хронические заболевания (необязательный пункт)', null=True, verbose_name='Хронические заболевания')),
                ('treatment', models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле)', null=True, verbose_name='Назначенное лечение')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dohhealth', to='database.doginfo')),
            ],
            options={
                'verbose_name': 'Здоровье собаки',
                'verbose_name_plural': 'Здоровье собак',
            },
        ),
        migrations.RemoveField(
            model_name='doghealthissues',
            name='dog',
        ),
        migrations.AddField(
            model_name='dogkennel',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogkennel', to='database.doginfo'),
        ),
        migrations.AlterField(
            model_name='catdates',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catdates', to='database.catinfo'),
        ),
        migrations.AlterField(
            model_name='dogdates',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dogdates', to='database.doginfo'),
        ),
        migrations.DeleteModel(
            name='CatHealthIssues',
        ),
        migrations.DeleteModel(
            name='DogHealthIssues',
        ),
    ]
