# Generated by Django 3.2.3 on 2025-03-22 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20250322_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogdates',
            name='dog',
        ),
        migrations.AddField(
            model_name='catinfo',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ориентировочная дата рождения (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catinfo',
            name='intake_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ориентировочная дата заселения в приют (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата заселения в приют'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catinfo',
            name='intake_place',
            field=models.TextField(blank=True, help_text='Откуда животное попало в приют?', null=True, verbose_name='Место изъятия'),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='is_at_shelter',
            field=models.BooleanField(default=True, help_text='Находится в приюте? Да(по умолчанию)/Нет', verbose_name='Находится в приюте'),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='outtake_date',
            field=models.DateField(blank=True, help_text='Дата убытия из приюта', null=True, verbose_name='Дата убытия из приюта'),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='outtake_reasons',
            field=models.TextField(blank=True, help_text='Причина убытия', null=True, verbose_name='Причина убытия'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ориентировочная дата рождения (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doginfo',
            name='intake_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ориентировочная дата заселения в приют (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата заселения в приют'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doginfo',
            name='intake_place',
            field=models.TextField(blank=True, help_text='Откуда животное попало в приют?', null=True, verbose_name='Место изъятия'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='is_at_shelter',
            field=models.BooleanField(default=True, help_text='Находится в приюте? Да(по умолчанию)/Нет', verbose_name='Находится в приюте'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='outtake_date',
            field=models.DateField(blank=True, help_text='Дата убытия из приюта', null=True, verbose_name='Дата убытия из приюта'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='outtake_reasons',
            field=models.TextField(blank=True, help_text='Причина убытия', null=True, verbose_name='Причина убытия'),
        ),
        migrations.DeleteModel(
            name='CatDates',
        ),
        migrations.DeleteModel(
            name='DogDates',
        ),
    ]
