# Generated by Django 3.2.3 on 2025-03-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20250322_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogkennel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dogkennel',
            name='group',
        ),
    ]
