# Generated by Django 3.2.3 on 2025-03-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20250322_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogKennelGroup',
        ),
    ]
