# Generated by Django 3.2.3 on 2025-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_delete_dogkennelgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='kennel',
            field=models.CharField(blank=True, choices=[('P1', 'П1'), ('P2', 'П2'), ('P3', 'П3'), ('P4', 'П4'), ('P5', 'П5'), ('P6', 'П6'), ('P7', 'П7'), ('P8', 'П8'), ('P9', 'П9'), ('P10', 'П10'), ('P11', 'П11'), ('P12', 'П12'), ('P13', 'П13'), ('P14', 'П14'), ('P15', 'П15'), ('P16', 'П16'), ('P17', 'П17'), ('P18', 'П18'), ('P19', 'П19'), ('P20', 'П20'), ('G1', 'Г1'), ('G2', 'Г2'), ('G3', 'Г3'), ('G4', 'Г4'), ('G5', 'Г5'), ('G6', 'Г6'), ('G7', 'Г7'), ('G8', 'Г8'), ('G9', 'Г9'), ('G10', 'Г10'), ('G11', 'Г11'), ('G12', 'Г12'), ('G13', 'Г13'), ('G14', 'Г14'), ('G15', 'Г15'), ('G16', 'Г16'), ('G17', 'Г17'), ('KSH1', 'КШ1'), ('KSH2', 'КШ2'), ('KSH3', 'КШ3'), ('KSH4', 'КШ4'), ('KSH5', 'КШ5'), ('KSH6', 'КШ6'), ('KSH7', 'КШ7'), ('KSH8', 'КШ8'), ('KSH9', 'КШ9'), ('GUARD', 'Охрана'), ('Mira', 'Мира')], default=None, help_text='Вольер', max_length=64, null=True, verbose_name='Вольер'),
        ),
        migrations.DeleteModel(
            name='DogKennel',
        ),
    ]
