# Generated by Django 5.2.4 on 2025-11-09 18:49

import database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_catinfo_description_remove_catinfo_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalPhoto',
            new_name='DogPhoto',
        ),
        migrations.CreateModel(
            name='CatDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='История появления животного в приюте', verbose_name='Биография')),
                ('character', models.TextField(help_text='Характер животного', verbose_name='Характер')),
                ('best_owner', models.TextField(blank=True, help_text='Кому подойдет (необязательное поле)', null=True, verbose_name='Лучшие владельцы для животного')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_description', to='database.catinfo')),
            ],
            options={
                'verbose_name': 'Описание кошки',
                'verbose_name_plural': 'Описания кошек',
            },
        ),
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=database.models.cat_image_upload_to, verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='database.catinfo', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фотография кошки',
                'verbose_name_plural': 'Фотографии кошек',
            },
        ),
    ]
