# Generated by Django 5.2.4 on 2026-03-20 12:25

import cats.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '__first__'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя животного', max_length=64, verbose_name='Имя')),
                ('color', models.CharField(help_text='Окрас животного', max_length=128, verbose_name='Окрас')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], default='M', help_text='Пол животного', max_length=1, verbose_name='Пол')),
                ('is_neutered', models.BooleanField(default=False, help_text='Кастрировано? Да/Нет(по умолчанию)', verbose_name='Кастрация')),
                ('birth_date', models.DateField(help_text='Ориентировочная дата рождения (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата рождения')),
                ('intake_date', models.DateField(help_text='Ориентировочная дата заселения в приют (с точностью до года, если что, ставим 1 января соответствующего года)', verbose_name='Дата заселения в приют')),
                ('is_at_shelter', models.BooleanField(default=True, help_text='Находится в приюте? Да(по умолчанию)/Нет', verbose_name='Находится в приюте')),
                ('outtake_date', models.DateField(blank=True, help_text='Дата убытия из приюта', null=True, verbose_name='Дата убытия из приюта')),
                ('outtake_reasons', models.TextField(blank=True, help_text='Причина убытия', null=True, verbose_name='Причина убытия')),
                ('intake_place', models.TextField(blank=True, help_text='Откуда животное попало в приют?', null=True, verbose_name='Место изъятия')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='database.owner', verbose_name='Владелец')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Кошка',
                'verbose_name_plural': 'Кошки',
            },
        ),
        migrations.CreateModel(
            name='CatHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Хронические заболевания (необязательный пункт)', null=True, verbose_name='Хронические заболевания')),
                ('treatment', models.TextField(blank=True, help_text='Назначенное лечение (необязательное поле), дописываем, не удаляя старое: даты, лекарство, дозировка,будет своеобразный архив', null=True, verbose_name='Назначенное лечение')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания', null=True, verbose_name='Примечания')),
                ('felv_status', models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Лейкоз у кисы: да/нет/неизвестно(по умолчанию)', max_length=1, verbose_name='Вирус лейкоза кошек')),
                ('fiv_status', models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Иммунодефицит у кисы: да/нет/неизвестно(по умолчанию)', max_length=1, verbose_name='Иммунодефицит')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_health', to='cats.catinfo')),
            ],
            options={
                'verbose_name': 'Здоровье кошки',
                'verbose_name_plural': 'Здоровье кошек',
            },
        ),
        migrations.CreateModel(
            name='CatDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='История появления животного в приюте', verbose_name='Биография')),
                ('character', models.TextField(help_text='Характер животного', verbose_name='Характер')),
                ('best_owner', models.TextField(blank=True, help_text='Кому подойдет (необязательное поле)', null=True, verbose_name='Лучшие владельцы для животного')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_description', to='cats.catinfo')),
            ],
            options={
                'verbose_name': 'Описание кошки',
                'verbose_name_plural': 'Описания кошек',
            },
        ),
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cats.models.cat_image_upload_to, verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cats.catinfo', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фотография кошки',
                'verbose_name_plural': 'Фотографии кошек',
            },
        ),
    ]
