# Generated by Django 5.2.4 on 2026-03-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_catinfo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cathealth',
            name='felv_status',
        ),
        migrations.RemoveField(
            model_name='cathealth',
            name='fiv_status',
        ),
    ]
