# Generated by Django 5.2.4 on 2026-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_remove_cathealth_felv_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathealth',
            name='felv_status',
            field=models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Лейкоз у кисы: да/нет/неизвестно(по умолчанию)', max_length=1, verbose_name='Вирус лейкоза кошек'),
        ),
        migrations.AddField(
            model_name='cathealth',
            name='fiv_status',
            field=models.CharField(choices=[('Y', 'Положительно'), ('N', 'Отрицательно'), ('U', 'Неизвестно')], default='U', help_text='Иммунодефицит у кисы: да/нет/неизвестно(по умолчанию)', max_length=1, verbose_name='Иммунодефицит'),
        ),
    ]
