# Generated by Django 5.2.4 on 2026-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cathealth_felv_status_cathealth_fiv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfo',
            name='priority',
            field=models.IntegerField(default=0, help_text='Чем больше — тем выше в списке', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Срочно ищет дом'),
        ),
    ]
