# Generated by Django 5.2.4 on 2026-03-24 13:29

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_catinfo_priority_catinfo_urgent'),
        ('database', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catinfo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='database.TaggedAnimal', to='database.AnimalTag', verbose_name='Tags'),
        ),
    ]
